'use strict';

const { FixedWindowController } = require('../bitbrowser/window-controller');
const { Sub2ApiAdminClient, parseCodeInput } = require('../sub2api/admin-client');

class OAuthFlow {
  constructor({ sub2api = new Sub2ApiAdminClient(), browser = new FixedWindowController() } = {}) {
    this.sub2api = sub2api;
    this.browser = browser;
  }

  async start({ proxyId, incognito = false } = {}) {
    const authorization = await this.sub2api.generateOpenAiAuthUrl({ proxyId });
    const session = await this.browser.open({ url: authorization.authUrl, incognito });
    return { authorization, session };
  }

  async exchange({ authorization, input, proxyId } = {}) {
    if (!authorization?.sessionId || !authorization?.state) throw new Error('An authorization generated by start() is required');
    const supplied = parseCodeInput(input);
    if (supplied.state && supplied.state !== authorization.state) {
      throw new Error('OAuth callback state does not match the generated authorization session');
    }
    return this.sub2api.exchangeOpenAiCode({
      sessionId: authorization.sessionId,
      code: supplied.code,
      state: authorization.state,
      proxyId,
    });
  }

  async run({ proxyId, incognito = false, timeoutMs = 10 * 60_000 } = {}) {
    const started = await this.start({ proxyId, incognito });
    try {
      const callback = await started.session.waitForCallback({ timeoutMs });
      const result = await this.exchange({ authorization: started.authorization, input: callback.state ? `http://localhost:1455/auth/callback?code=${encodeURIComponent(callback.code)}&state=${encodeURIComponent(callback.state)}` : callback.code, proxyId });
      return { authorization: started.authorization, callback, result, session: started.session };
    } finally {
      // Disconnect Playwright but leave us001_codex open for review/re-entry.
      await this.browser.release({ closeWindow: false });
    }
  }

  async release({ closeWindow = false } = {}) {
    return this.browser.release({ closeWindow });
  }
}

module.exports = { OAuthFlow };
